In [5]:
import pandas as pd
from sqlalchemy import create_engine
from mysecrets import user, password

engine = create_engine(f'postgresql://{user}:{password}@localhost:5432/book_recs')

In [7]:
pd.read_sql(
    """
    SELECT *
    FROM GOODREADS_BOOKS
    WHERE TITLE LIKE 'Slaughterhouse Five'
    """,
    engine
)

,isbn,text_reviews_count,series,country_code,language_code,asin,is_ebook,average_rating,kindle_asin,similar_books,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,NaN,13,[],US,eng,B000FA5QZO,true,4.06,B003XVYLDU,"['91494', '22584', '92508', '243598', '12467',...",...,1.0,,2001.0,https://www.goodreads.com/book/show/6308664-sl...,https://images.gr-assets.com/books/1296250089m...,6308664,342,1683562,Slaughterhouse Five,Slaughterhouse Five
1,60735554.0,6,[],US,eng,,false,4.06,,"['91494', '22584', '92508', '243598', '12467',...",...,11.0,,2003.0,https://www.goodreads.com/book/show/3271073-sl...,https://images.gr-assets.com/books/1433476592m...,3271073,55,1683562,Slaughterhouse Five,Slaughterhouse Five
2,NaN,1,[],US,,,false,4.06,B003XVYLDU,"['91494', '22584', '92508', '243598', '12467',...",...,NaN,Abridged,NaN,https://www.goodreads.com/book/show/9618.Slaug...,https://images.gr-assets.com/books/1433478355m...,9618,19,1683562,Slaughterhouse Five,Slaughterhouse Five
3,NaN,32,[],US,eng,,false,4.06,,"['91494', '22584', '92508', '243598', '12467',...",...,NaN,alt cover dell 8029 0440080290,1971.0,https://www.goodreads.com/book/show/1074901.Sl...,https://images.gr-assets.com/books/1395584346m...,1074901,181,1683562,Slaughterhouse Five,Slaughterhouse Five
4,844663662.0,145,[],US,eng,,false,4.06,B003XVYLDU,"['91494', '22584', '92508', '243598', '12467',...",...,NaN,,NaN,https://www.goodreads.com/book/show/28131.Slau...,https://s.gr-assets.com/assets/nophoto/book/11...,28131,1187,1683562,Slaughterhouse Five,Slaughterhouse Five
5,710090049.0,4,[],US,eng,,false,4.06,,"['91494', '22584', '92508', '243598', '12467',...",...,NaN,First Laurel Edition,1988.0,https://www.goodreads.com/book/show/13449084-s...,https://images.gr-assets.com/books/1488747300m...,13449084,31,1683562,Slaughterhouse Five,Slaughterhouse Five
6,60799161.0,45,[],US,,,false,4.06,,"['91494', '22584', '92508', '243598', '12467',...",...,11.0,Digital,2003.0,https://www.goodreads.com/book/show/9568528-sl...,https://images.gr-assets.com/books/1355127851m...,9568528,155,1683562,Slaughterhouse Five,Slaughterhouse Five